ecom_project/cart/urls.py
from django. urls import path
from.import views


app_name='cart'

urlpatterns=[
    path('add/<int:product_id>/',views.add_cart,name='add_cart'),
    path('',views.cart_detail,name='cart_detail'),
    path('remove/<int:product_id>/',views.cart_remove,name='cart_remove'),
    path('full_remove/<int:product_id>/',views.full_remove,name='full_remove')
]

ecom_project/ecom_app/urls.py
from django.urls import path
from.import views
app_name='ecom_app'
urlpatterns = [

    path('',views.allprodcat,name='allprodcat'),
    path('<slug:c_slug>/',views.allprodcat,name='products_by_category'),
    path('<slug:c_slug>/<slug:p_slug>/',views.prodetail,name='prodet')

]

ecom_project/ecom_project/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('ecom/',include('ecom_app.urls')),
    path('search/',include('search_app.urls')),
    path('cart/',include('cart.urls'))
]



if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

ecom_project/search_app/urls.py
from django.urls import path
from.import views

app_name='search_app'

urlpatterns=[
    path('',views.searchresult,name='searchresult'),
]

ecom_project/cart/models.py
from django.db import models
from ecom_app.models import products
# Create your models here.

class cart(models.Model):
    cart_id=models.CharField(max_length=250, blank=True)
    date_added=models.DateField(auto_now_add=True)

    class Meta:
        db_table='cart'
        ordering=['date_added']

    def __str__(self):
        return '{}'.format(self.cart_id)

class cartitem(models.Model):
    product=models.ForeignKey(products,on_delete=models.CASCADE)
    cart=models.ForeignKey(cart,on_delete=models.CASCADE)
    quantity=models.IntegerField()
    active=models.BooleanField(default=True)

    class Meta:
        db_table='cartitem'

    def sub_total(self):
        return '{}'.format(self.product.prize * self.quantity)


    def __str__(self):
        return self.product

ecom_project/ecom_app/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class Category(models.Model):
    name=models.CharField(max_length=250,unique=True)
    slug=models.SlugField(max_length=250,unique=True)
    description=models.TextField()
    image=models.ImageField(upload_to='category')

    class Meta:
        ordering=('name',)
        verbose_name='category'
        verbose_name_plural='categories'

    def get_url(self):
        return reverse('ecom_app:products_by_category', args=[self.slug])


    def __str__(self):
        return '{}'.format(self.name)


    # def get_url(self):
       # return reverse('ecom_app:products_by_category', args=self.slug)

class products(models.Model):
    name=models.CharField(max_length=250,unique=True)
    slug=models.SlugField(max_length=250,unique=True)
    description=models.TextField(blank=True)
    prize=models.DecimalField(max_digits=10,decimal_places=2)
    category=models.ForeignKey(Category,on_delete=models.CASCADE)
    image=models.ImageField(upload_to='product',blank=True)
    stock=models.IntegerField()
    available=models.BooleanField(default=True)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now=True)


    class Meta:
        ordering = ('name',)
        verbose_name = 'product'
        verbose_name_plural = 'products'

    def get_url(self):
        return reverse('ecom_app:prodet', args=[self.category.slug,self.slug])

    def __str__(self):
        return '{}'.format(self.name)

ecom_project/search_app/models.py
from django.db import models

# Create your models here.

ecom_project/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from ecom_app.models import products
from.models import cart,cartitem
from django.core.exceptions import ObjectDoesNotExist


def _cart_id(request):
    Cart=request.session.session_key
    if not Cart:
        Cart = request.session.create()

    return Cart

def add_cart(request,product_id):
    product=products.objects.get(id=product_id)
    try:
        Cart=cart.objects.get(cart_id=_cart_id(request))
    except cart.DoesNotExist:
        Cart=cart.objects.create(cart_id=_cart_id(request))
        Cart.save()
    try:
        cart_item=cartitem.objects.get(product=product,cart=Cart)
        if cart_item.quantity < cart_item.product.stock:
            cart_item.quantity+=1
        cart_item.save()
    except cartitem.DoesNotExist:
        cart_item=cartitem.objects.create(product=product,quantity=1,cart=Cart)
        cart_item.save()

    return redirect('cart:cart_detail')

def cart_detail(request,total=0, counter=0,cart_items=None):
    try:
        Cart=cart.objects.get(cart_id=_cart_id(request))
        cart_items=cartitem.objects.filter(cart=Cart,active=True)
        for cart_item in cart_items:
            total += (cart_item.product.prize * cart_item.quantity)
            counter += cart_item.quantity
    except ObjectDoesNotExist:
        pass
    return render(request,'cart.html',dict(cart_items=cart_items,total=total,counter=counter))

def cart_remove(request,product_id):
    Cart=cart.objects.get(cart_id=_cart_id(request))
    produt=get_object_or_404(products,id=product_id)
    cart_item=cartitem.objects.get(product=produt,cart=Cart)
    if cart_item.quantity > 1:
        cart_item.quantity -= 1
        cart_item.save()
    else:
        cart_item.delete()
    return redirect('cart:cart_detail')
def full_remove(request,product_id):
    Cart = cart.objects.get(cart_id=_cart_id(request))
    produt = get_object_or_404(products, id=product_id)
    cart_item = cartitem.objects.get(product=produt, cart=Cart)
    cart_item.delete()
    return redirect('cart:cart_detail')

ecom_project/ecom_app/views.py
from django.http import HttpResponse
from django.shortcuts import render,get_object_or_404
from.models import Category,products
from django.core.paginator import Paginator,EmptyPage,InvalidPage

# Create your views here.


def allprodcat(request,c_slug=None):
    c_page=None
    product_list=None
    if c_slug!=None:
        c_page=get_object_or_404(Category,slug=c_slug)
        product_list=products.objects.all().filter(category=c_page,available=True)
    else:
        product_list=products.objects.all().filter(available=True)
    paginator=Paginator(product_list,6)
    try:
        page=int(request.GET.get('page','1'))
    except:
        page=1
    try:
        product=paginator.page(page)
    except (EmptyPage,InvalidPage):
        product=paginator.page(paginator.num_pages)
    return render(request,'category.html',{'category':c_page,'product':product})

def prodetail(request,c_slug,p_slug):
    try:
        product=products.objects.get(category__slug=c_slug,slug=p_slug)
    except Exception as e:
        raise e
    return render(request,'product.html',{'product':product})

ecom_project/search_app/views.py
from django.shortcuts import render
from ecom_app.models import products
from django.db.models import Q


def searchresult(request):
    product=None
    query=None
    if 'q' in request.GET:
        query=request.GET.get('q')
        product=products.objects.all().filter(Q(name__contains=query) | Q(description__contains=query))
        return render(request,'search.html',{'query':query,'product':product})

ecom_project/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="{% block metadescription %} {% endblock %}">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">

<!--    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">-->
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
<div class="container-fluid">
{% include 'header.html' %}
{% include 'navbar.html' %}
{% block content %}
    {% endblock %}
    </div>
{% include 'footer.html' %}
<!--    <script src="{% static 'js/3.5.0/jquery.min.js' %}"></script>-->
    <script src="https://kit.fontawesome.com/4cd7a0f63f.js" crossorigin="anonymous"></script>
    <script src="{% static 'js/jquery-3.3.1.slim.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>


</body>
</html>

ecom_project/templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
this is cart page
{% endblock %}
{% block title %}
 cart
{% endblock %}
{% block content %}
{% if not cart_items %}
<div>
  <div class="text-center">
    <br>
    <h1 class="text-center my_title">empty cart</h1>
    <br>
    <p class="text-center">to redirect click<a href="{% url 'ecom_app:allprodcat' %}">here</a></p>

  </div>
</div>
{% else %}
<div>
  <div class="text-center">
    <br>
    <h1 class="text-center my_title">your shopping cart</h1>
    <br>
  </div>
  <div class="row mx-auto">
    <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
      <table class="table my_custom_table">
        <thead class="my_custom_thead">
        <tr>
          <th colspan="5">
            Your items
          </th>
        </tr>
        </thead>
        <tbody>
        {% for cart_item in cart_items %}
        <tr>
          <td>
            <a href="cart_item.product.get_absolute_url"><img src="{{cart_item.product.image.url}}" alt="" style="width:100px;height:100px;" class="float-left rounded custom_image"></a>
          </td>
          <td class="text-left">
            {{cart_item.product.name}}
            <br>
            SKU:{{cart_item.product.id}}
            <br>
            price:{{cart_item.product.prize}}
            <br>
            Qty:{{cart_item.quantity}}
            <br>
            {{cart_item.product.description}}

          </td>
          <td>
            ₹ {{cart_item.sub_total}}
          </td>
          {% if cart_item.quantity < cart_item.product.stock %}
          <td>
            <a href="{% url 'cart:add_cart' cart_item.product.id %}" class="custom_a"> <i class="fa-solid fa-circle-plus custom_icon"></i></a>
            &nbsp;<a href="{% url 'cart:cart_remove' cart_item.product.id %}" class="custom_a"><i class="fa-solid fa-circle-minus custom_icon"></i></a>
            &nbsp;<a href="{% url 'cart:full_remove' cart_item.product.id %}" class="custom_icon"><i class="fa-solid fa-trash-can custom_icon"></i></a>
          </td>
          {% else %}
          <td>

            &nbsp;<a href="{% url 'cart:cart_remove' cart_item.product.id %}" class="custom_a"><i class="fa-solid fa-circle-minus custom_icon"></i></a>
            &nbsp;<a href="{% url 'cart:full_remove' cart_item.product.id %}" class="custom_icon"><i class="fa-solid fa-trash-can custom_icon"></i></a>
          </td>
          {% endif %}
        </tr>
        {% endfor %}
        </tbody>
      </table>
    </div>

<div class="col-12 col-sm-12 col-lg-6 text-center">
  <table class="table my_custom_table">
    <thead class="my_custom_thead">
    <tr>
      <th>
        checkout
      </th>
    </tr>
    </thead>
    <tbody>
  <tr>
    <td>
      review out shopping experience
    </td>
  </tr>
    <tr>
      <td class="text-center">your total is : <strong>{{ total }}</strong></tdclass>
    </tr>
  </tbody>
    <tr>

    </tr>
  </table>
  <div class="mx-auto">
  <a href="{% url 'ecom_app:allprodcat' %}" alt="" class="btn btn-secondary">continue shopping</a>
  </div>
</div>
{% endif %}
<div>
  <div>

  </div>
</div>

{% endblock %}

ecom_project/templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
 {% if category %}
  {{category.description|truncatewords:155}}
{% else %}
  welcome to clothes store where you can buy different items.....
{% endif %}
{% endblock %}

{% block title %}
 {% if category %}
  {{category.name}}---my store
{% else %}
 new store
{% endif %}
{% endblock %}
{% block content %}
{% if category %}

 <div class="row my_row_class">
  <div class="mx_auto">
  <p><a href="{% url 'ecom_app:allprodcat' %}">See Our Product Collections: {{category.name}}</a></p>
 </div>
  </div>

{% endif %}
<div class="mx_auto">
 {% if category %}
 <center>
 <img class="my_image" src="{{category.image.url}}" alt="{{category.name}}">
  </center>
</div>
<br>
<div>
 <h1 class="text-center my_title">{{category.name}}</h1>
 <p class="text-justify">{{category.description}}</p>
</div>
{% else %}
<div class="container-fluid">
 <div>
  <center>
<img class="my_image my_image_padding" src="{% static 'img/cbanner.png' %}" alt="Our Products" width="1500px;">
   </center>
  </div>
</div>
<br>
<div>
 <center>
 <h1 class="my_title">Our Products Collections</h1>
  </center>
 <div class="container-fluid">
  <div>
 <p class="text-justify">The word Lorem Ipsum is derived from the Latin word which means “pain itself”. It is a kind of a text filler tool that is used by the webmaster on the website.Basically, this tool is used to create
  dummy content on the website when it’s new. Why Lorem Ipsum Is Used? It helps the designer plan where the content will sit. It helps in creating drafts of the content on the pages of the website. It
  originates from the Latin textbut is seen as gibberish.Sometimes, the reader gets distracted while creating or working on the website. That’s why this language is important.This tool makes the work easier
  for the webmaster.</p>
   </div>
  </div>
</div>
{% endif %}
<div class="container">
 <div class="row mx_auto">
  {% for pro in product.object_list %}
  <div class="my_bottom_margin col-9 col-sm-12 col-md-4  col-lg-4">
   <div class="card text-center" style="min-width:1rem">
    <a href="{{pro.get_url}}"><img class="card-img-top my_image" src="{{pro.image.url}}" alt="{{pro.name}}"></a>
    <div class="card-body">
     <h4>{{pro.name}}</h4>
     <p>{{pro.prize}}</p>
    </div>
   </div>
   <br>
  </div>
  {% endfor %}
</div>
 </div>
<div class="mx_auto">
 {% if product.paginator.num_pages > 1 %}


 <div class="text-center">
  {% for pg in product.paginator.page_range %}
  <a href="?page={{pg}}" class="btn btn-light btn-sm {% if product.number == pg %} active {% endif %}">{{pg}}</a>
  {% endfor %}
 </div>
 {% endif %}
</div>
 <br>
</div>

{% endblock %}

ecom_project/templates/footer.html
<div class="footer navbar-fixed-bottom my_footer">
    <p class="text-center">&copy; clothes shop pvt ltd</p>
</div>

ecom_project/templates/header.html
{% load static %}

<header>
    <center>
        <a href="{% url 'ecom_app:allprodcat' %}"><img src="{% static 'img/fashions.png' %}" alt="logoimage"></a>
    </center>
</header>

ecom_project/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-transparent bg-light">

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mx-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'ecom_app:allprodcat' %}">Home</a>
      </li>
      <li class="nav-item dropdown {% if 'ecom_app' in request.path %} active {% endif %}">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
          Shop
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="{% url 'ecom_app:allprodcat' %}">all product</a>
          {% for cat in links %}
          <a class="dropdown-item" href="{{cat.get_url}}">{{cat.name}}</a>
          {% endfor %}
        </div>
      </li>
      {% if item_count > 0 %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'cart:cart_detail' %}"><i class="fa-solid fa-cart-shopping fa-flip"></i>({{item_count}})</a>
      </li>
      {% endif %}
     <li>
    <form class="form-inline my-2 my-lg-0" action="{% url 'search_app:searchresult' %}" method="get">
      {% csrf_token %}
      <input class="form-control mr-sm-2" type="search" placeholder="Search" name="q" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit"><i class="fa-solid fa-magnifying-glass fa-beat"></i></button>
    </form>
      </li>
       </ul>
  </div>
</nav>


















<!--<nav>-->
<!--  <div>-->
<!--    <p><a href="{% url 'ecom_app:allprodcat' %}">all product</a></p>-->
<!--    {% for cat in links %}-->
<!--    <p><a href="{{cat.get_url}}">{{cat.name}}</a></p>-->
<!--    {% endfor %}-->
<!--  </div>-->
<!--</nav>-->

















































































<!--<nav>-->
<!--<div class="dropdown">-->
<!--  <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">-->
<!--    Dropdown button-->
<!--  </button>-->
<!--  <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">-->
<!--    <a class="dropdown-item" href="{% url 'ecom_app:allprodcat' %}">all product</a>-->
<!--    {% for cat in links %}-->
<!--    <a class="dropdown-item" href="{{cat.get_url}}">{{cat.name}}</a>-->
<!--    {% endfor %}-->
<!--    <a class="dropdown-item" href="#">Something else here</a>-->
<!--  </div>-->
<!--</div>-->
<!--</nav>-->

ecom_project/templates/product.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
  {{product.description}}
{% endblock %}
{% block title %}
 {% if category %}
  {{product.name}}/{{product.category}}
{% endif %}
{% endblock %}
{% block content %}
<div class="row my_product_row_class">
  <div class="mx_auto">
   <p><a href="{% url 'ecom_app:allprodcat' %}">Home</a> | <a href="{{product.category.get_url}}">{{product.category}}</a></p>
  </div>
</div>
<div class="container">
<br>
<div class="row">
    <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
        <div style="min-width:18rem;">
            <img src="{{product.image.url}}" alt="{{product.name}}">
        </div>
    </div>
    <div class="col-12 col-sm-12 col-md-12 col-lg-6">
        <div>
        <h2 class="my_prod_title">{{product.name}}</h2>
        <p>{{product.price}}</p>
        <p class="my_title">PRODUCT DESCRIPTION</p>
        <p class="text-justify my_prod_text">{{product.description}}</p>
        {% if product.stock <= 0 %}
          <p class="text-justify my_prod_text"><b>Out of Stock</b></p>
        {% else %}
        <a class="btn btn-info" href="{% url 'cart:add_cart' product.id %}">Add to Cart</a><br>
        {% endif %}
    </div>
    </div>
   </div>
</div>
{% endblock %}

ecom_project/templates/search.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
you can buy products here..
{% endblock %}
{% block title %}
 search
{% endblock %}
{% block content %}
<div>
    <p class="text-center my_search_title">you have searched for:<b>"{{query}}"</b></p>
</div>
 <div class="row mx_auto">
  {% for pro in product %}
  <div class="my_bottom_margin col-9 col-sm-12 col-md-4  col-lg-4">
   <div class="card text-center" style="min-width:1rem">
    <a href="{{pro.get_url}}"><img class="card-img-top my_image" src="{{pro.image.url}}" alt="{{pro.name}}"></a>
    <div class="card-body">
     <h4>{{pro.name}}</h4>
     <p>{{pro.prize}}</p>
    </div>
   </div>
   <br>
  </div>
     {% empty %}
     <div class="row  mx-auto ">
         <p class="text-center my_search_title">o result found</p>
     </div>
  {% endfor %}

 </div>
{% endblock %}